### ISSUE TITLE
installing and setting up the server

### ISSUE THREAD

**Issue by dkswedens** [jor3l/broadlinkrm-ifttt#26]
Hi, I was wondering if you could help me out abit.
I installed npm using npm install in terminal
I then used "npm install broadlink-rm-server"
and installed the repo.
Now, how do I create a index.js and command.js?
I'm very new to the rasppi world so I'm unfamiliar with most of this, do you have time to put aside to help me out?

Best regards,
-d

**Comment by dkswedens** [comment]
pi@raspberrypi:~/node_modules/broadlink-rm-server $ node index
internal/modules/cjs/loader.js:498
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
  ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /home/pi/node_modules/broadlink-rm-server/node_modules/uuid/package.json
    at applyExports (internal/modules/cjs/loader.js:498:9)
    at resolveExports (internal/modules/cjs/loader.js:514:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:642:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1017:27)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/pi/node_modules/broadlink-rm-server/index.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'

**Comment by jor3l** [comment]
Hey! long time since I used this, most lilkely that package was updated and no longer includes the v4 export, let me install and fix that, I'll report back

**Comment by srijansaxena11** [comment]
did you get it working? how?
